---
title: "SF: High vs. Low"
output: html_notebook
---


```{r}
library(janitor)
library(here)
library(afex)
library(emmeans)
library(Rmisc)
library(data.table)
library(tidyr)
```

# Low Testing Data Load

```{r}


setwd(here::here('SF_data', 'Gorilla_data_low'))

data=here::here('SF_data', 'Gorilla_data_low')  # path to data files

file_list=list.files(data, pattern=".csv") # list of data files
 
# read in all files
datasetlow <-
  do.call("rbind", lapply(file_list, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
    fread(files, header=TRUE, sep=",", na.strings = "", fill=TRUE)})) #fread makes reading in files quick
#

```

```{r}
library(lubridate)

low<-datasetlow %>% 
  janitor::clean_names(.) %>% 
  dplyr::mutate(date=as.Date(utc_date)) %>%
  dplyr::filter(date=="08/06/2020" |date=="09/06/2020" , zone_type=="response_button_text")

#response as character
low$response<-as.character(low$response)

low$testexpect<-"low"


```

#High Testing Data Load
```{r}


setwd(here::here('SF_data', 'Gorilla_data_high'))

data=here::here('SF_data', 'Gorilla_data_high')  # path to data files

file_list=list.files(data, pattern=".csv") # list of data files
 
# read in all files
highdata <-
  do.call("rbind", lapply(file_list, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
    fread(files, header=TRUE, sep=",", na.strings = "", fill=TRUE)})) #fread makes reading in files quick
#

```

```{r}
library(lubridate)
# a batch of Ss we run before preregistration that should not be included in the analysis
high <-highdata %>% 
  janitor::clean_names(.) %>% 
  mutate(date=as.Date(utc_date)) %>%
  dplyr::filter(date=="08/06/2020" | date=="0009/07/2020" |date=="0010/07/2020" | date=="09/06/2020", zone_type=="response_button_text")

#response as character
high$response<-as.character(high$response)

high$testexpect<-"high"

```

#Combine 
```{r}

high_low<-rbind(high, low)

```

```{r}
#get Rts

datasetlow$testexpt<-"low"
highdata$testexpt<-"high"

rt_high_low <- rbind(datasetlow, highdata)

rt<-rt_high_low %>% janitor::clean_names(.) %>%  dplyr::filter(zone_type=="continue_button", display=="study") 

# get RT
rt$reaction_time<-as.numeric(rt$reaction_time)

rt1<- rt %>% 
  dplyr::group_by(participant_private_id , condition, testexpt) %>% 
  dplyr::summarise(mean=mean(reaction_time, na.rm=TRUE))

rt2=rt1 %>% pivot_wider(names_from=condition, values_from = "mean")

write.csv(rt2, file="rt_high_low.csv")

#ttestBF(x=rt2$normal, y=rt2$SF, paired=TRUE, data=rt2)
#t.test(x=rt2$normal, y=rt2$SF, paired=TRUE, data=rt2)

#6.67
```


```{r}
#JOls

 #get Rts

jol_high_low <- rbind(datasetlow, highdata)

jols<-jol_high_low %>% janitor::clean_names(.) %>%  dplyr::filter(zone_type=="response_slider_endValue" | zone_type=="response_text_entry") 

# get RTjols1

jols$response<-as.numeric(jols$response)


jols1<- jols %>% 
  dplyr::select(participant_private_id, response, testexpt) %>%
  mutate(cond=rep(1:2, 327), font=ifelse(cond==1, "SF", "A")) %>%
  select(-cond)%>%
  pivot_wider(names_from="font", values_from="response")

jols1<-na.omit(jols1)

write.csv(jols1, file="low_high_jols.csv")

#6.67

```

```{r}
#response as character

ex4=high_low %>% mutate(condition1= case_when( 
  condition == "SF" ~ "Sans Forgetica", 
  condition =="normal" ~  "Arial", 
), isold= case_when (
  old_new== "old" ~ 1, 
  old_new== "new" ~ 0), 
sayold=case_when( 
  response=="old"~ 1, 
  response=="new" ~ 0, 
  ))



#classic SDT for those wanting to compare
sdt <- ex4 %>% 
  dplyr::mutate(type = "hit",
         type = ifelse(isold==1 & sayold==0, "miss", type),
         type = ifelse(isold==0 & sayold==0, "cr", type),  # Correct rejection
         type = ifelse(isold==0 & sayold==1, "fa", type))  # False alarm
sdt <- sdt %>% 
  dplyr::group_by(participant_private_id, type, condition1, testexpect) %>% 
  dplyr::summarise(count = n()) %>% 
  spread(type, count)  # Format data to one row per person

sdt <- sdt %>% 
  group_by(participant_private_id, condition1, testexpect)%>%
  dplyr::mutate(hr = hit / (hit+miss),
         fa = fa / (fa+cr)) %>%
  dplyr::mutate(hr=case_when(
    is.na(hr) ~ 0.99,
    TRUE ~ hr), 
    fa=case_when(
      is.na(fa)  ~ 0.01,
    TRUE ~ fa),
     zhr=qnorm(hr), 
     zfa=qnorm(fa), 
    dprime = zhr-zfa) %>%
  ungroup()

sdt

```

```{r}
sdt1=sdt  %>% select(participant_private_id, condition1, testexpect, hr, fa) %>% 
  pivot_longer(hr:fa, names_to="type") %>%
  dplyr::mutate(isold=case_when(type=="hr" ~ "Old", type=="fa" ~ "New"))

sdt1$isold<-factor(sdt1$isold, levels=c("Old", "New"))

sdt1$Condition<-factor(sdt1$condition1, levels=c("Sans Forgetica", "Arial"))


highlowaov=sdt  %>% select(participant_private_id, condition1, testexpect, dprime)


```

```{r}
#ANOVA


a1 <- aov_ez("participant_private_id", "dprime", highlowaov, 
             between = c("testexpect"), within=c("condition1")) # mixed

summary(a1)


sfgen_wsci=summarySEwithin(data = highlowaov, measurevar = "dprime",
                       withinvars = "condition1", betweenvars = "testexpect", idvar = "participant_private_id")

bf = anovaBF(dprime ~ condition1*testexpect + participant_private_id, highlowaov, 
          whichRandom="participant_private_id")



a1
```

```{r}
means <- sdt1 

oldnewsub=summarySEwithin(data = means, measurevar = "value",
                       withinvars = c("condition1", "isold","type"), betweenvars=c("testexpect"), idvar = "participant_private_id")
```


```{r}
library(see)
bold <- element_text(face = "bold", color = "black", size = 14) 

p1<- ggplot(means, aes(condition1, value, fill=condition1))+
  facet_grid(.~testexpect+isold) + 
  geom_violin() + 
  geom_jitter2(width=0.11, alpha=.5)+ 
  geom_line(data=oldnewsub,aes(y=value, group=1), size=1)+ 
  geom_pointrange(data=oldnewsub, aes(y=value, ymin=value-ci, ymax=value+ci), size=1, color="white")+ 
  theme_bw(base_size=14)+
  labs(y="Pr Saying Old", x="Font Type") + 
  theme(legend.position = "none") + 
  theme(axis.text=bold) 


#oldnew=brm(glmm2, data=ex3, family=bernoulli(link="identity"), prior=Priors, sample_prior = TRUE,  cores=6, inits = 0, control = list(adapt_delta = .9), iter=3000)

p1

```


```{r,  fig.width=8, fig.height=12}

sdt$condition1<-factor(sdt$condition1, levels=c("Arial", "Sans Forgetica"))


dsw=summarySEwithin(data = sdt, measurevar = "dprime",
                       withinvars = "condition1", betweenvars = "testexpect",  idvar = "participant_private_id")
 
 
 
p2<- ggplot(sdt, aes(condition1, dprime, fill=condition1))+
  geom_violin() + facet_grid(~testexpect) + 
  geom_jitter2(width=0.11, alpha=.5)+ 
  geom_line(data=dsw,aes(y=dprime, group=1), size=2)+ 
  geom_pointrange(data=dsw, aes(y=dprime, ymin=dprime-se, ymax=dprime+se), size=1, color="white")+ 
  theme_bw(base_size=14)+
  labs(y="Sensitivity (d')", x="Font Type") + 
  theme(legend.position = "none") + 
  theme(axis.text=bold)

p2


patchwork1= p1/ p2 
patchwork1 + plot_annotation(tag_levels = 'A')


```
