---
title: "Cued_recall"
author: "Jason Geller"
date: "6/22/2020"
output: html_document
---
# read in packages
```{r}
library(janitor)
library(here)
library(afex)
remotes::install_github("npm27/lrd")
library(BayesFactor)
library(lrd)
library(emmeans)
library(Rmisc)
library(data.table)
library(tidyr)
library(see)
```

# read in  data

```{r}

setwd(here::here("cue_recall", "gorilla_data"))

data=here::here("cue_recall", "gorilla_data") # path to data files

file_list=list.files(data, pattern=".csv") # list of data files
 
# read in all files
dataset <-
  do.call("rbind", lapply(file_list, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
    fread(files, header=TRUE, sep=",", na.strings = "", fill=TRUE)})) #fread makes reading in files quick
#

```


```{r}
#acc based on perfect match
dd<-dataset %>% 
  janitor::clean_names(.) %>% 
  dplyr::filter(display=="test", zone_type=="response_text_entry") %>%
  mutate(target=tolower(target), response=tolower(response),  acc=ifelse(target==response, 1, 0)) 

dd[is.na(dd)] <- 0
#acc based on perfect match
#dd_acc<-dd  %>%
 # dplyr::group_by(participant_private_id, font) %>%
 # dplyr::summarise(mean_acc=mean(acc)) %>%
 # pivot_wider(names_from="font", values_from = "mean_acc")


#acc baed on 80% match from lrd
# Compute percent match for cued-recall
dd_lrd <- dplyr::select(dd, participant_private_id, response, target, font)

matched = percent_match.cr(dd_lrd$response, key = dd_lrd$target, id = dd_lrd$participant_private_id)# Now score the output using a 75% match criteria
# Note that score_recall automatically stores output in a .csv file
score_recall.cr(matched, cutoff = .80)
#saves file as output
#read_file

lrd_out<-read.csv(here::here("cue_recall", "summary_data", "cued",  "lrd_80_score.csv"))

dd_acc<-lrd_out %>%
  dplyr::group_by(id, font) %>%
  dplyr::summarise(mean_acc=mean(Scored)) %>%
  pivot_wider(names_from="font", values_from = "mean_acc")

t.test(x=dd_acc$a, y=dd_acc$sf, paired=TRUE, data=dd_acc)
```

```{r}
#get Rts
rt<-dataset %>% janitor::clean_names(.) %>%  dplyr::filter(zone_type=="continue_button", display=="study") 

# get RT
rt$reaction_time<-as.numeric(rt$reaction_time)
rt1<- rt %>% 
  dplyr::group_by(participant_private_id , font) %>% 
  dplyr::summarise(mean=mean(reaction_time, na.rm=TRUE))

rt2=rt1 %>% pivot_wider(names_from=font, values_from = "mean")


ttestBF(x=rt2$a, y=rt2$sf, paired=TRUE, data=rt2)
t.test(x=rt2$a, y=rt2$sf, paired=TRUE, data=rt2)

#write.csv(rt2, file="cued_rt_summary.csv")
```


```{r}
#JOls

 #get Rts
jols<-dataset %>% janitor::clean_names(.) %>%  dplyr::filter(display=="JOLs", zone_type=="response_text_entry")

# get RT
jols$rsponse<-as.numeric(jols$reposne)

jols1<- jols %>% 
  dplyr::select(participant_private_id, response) %>%
  mutate(cond=rep(1:2, 116), font=ifelse(cond==1, "SF", "A")) %>%
  dplyr::select(-cond)%>%
  pivot_wider(names_from="font", values_from="response")

```


```{r}
# t.test on JOL data
# take 1599998 provided weird number 
# some Ps did not provide a response or only provided one JOL 

jols1 <- jols1 %>%
  dplyr::filter(participant_private_id!="1599998") %>%
  mutate(SF=as.numeric(SF), A=as.numeric(A))

t.test(x=jols1$A, y=jols1$SF, paired=TRUE, data=jols1)


#write.csv(jols1, file="cued_jols_summary.csv")
```